pipeline {
  agent any
  environment {
      imageName = 'jaimesalas/my-api-app:latest'
  }
  stages {
    
    stage('Install dependencies') {
      agent {
        docker {
          image 'node:14-alpine'
          reuseNode true
        }
      }
      steps {
        dir('multibranch') {
            sh 'npm ci'
        }
      }
    }
    
    stage('Tests') {
      agent {
        docker {
          image 'node:14-alpine'
          reuseNode true
        }
      }
      steps {
        dir('multibranch') {
            sh 'npm test'
        }
      }
    }

    stage('Build image & push it to DockerHub') {
        steps {
            dir('multibranch') {
                script {
                    def dockerImage = docker.build(imageName)
                    withDockerRegistry([credentialsId: 'dockerhub-credentials', url: '']) {
                        dockerImage.push()
                        sh 'docker rmi $imageName'
                    }
                }
            }
        }
    }
  }
}
