pipeline {
    agent any 
    stages {
        stage('audit tools') {
            steps {
                sh '''
                    docker -v 
                    docker-compose -v
                    node -v
                    ls -l
                '''
            }
        }

        stage('unit tests') {
            steps {
                dir('integration-test/hangman-back') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }

        stage('integration test') {
            steps {
                dir('integration-test/hangman-back') {
                    echo 'run integration tests with Docker Compose'
                    sh 'docker-compose -f test-integration.yml up -d'
                    script {
                        def status = sh(script: 'docker wait test-integration', returnStdout: true)
                        // println status
                        def statusInt = status.toInteger()

                        if (statusInt != 0) {
                            throw new Exception(
                                "Integration tests failed you cna debug by removing d flag on docker compose"
                            )
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            dir('integration-test/hangman-back') {
                echo 'clean resources'
                sh 'docker-compose -f test-integration.yml down --rmi all -v'
            }
            cleanWs()
        }
    }
}
